# Generated by Django 5.2.5 on 2025-08-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Айди')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('region', models.CharField(max_length=100, verbose_name='Регион')),
                ('okrug', models.CharField(max_length=100, verbose_name='Округ')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Podsh',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('POLN', models.CharField(blank=True, max_length=255, null=True)),
                ('SLITN', models.CharField(blank=True, max_length=255, null=True)),
                ('OSNOVA', models.CharField(blank=True, max_length=255, null=True)),
                ('ANALOG', models.CharField(blank=True, max_length=50, null=True)),
                ('FIRMA', models.CharField(blank=True, max_length=20, null=True)),
                ('WES', models.CharField(blank=True, max_length=15, null=True)),
                ('MIN', models.CharField(blank=True, max_length=15, null=True)),
                ('MAX', models.CharField(blank=True, max_length=15, null=True)),
                ('SHIR', models.CharField(blank=True, max_length=15, null=True)),
                ('ISKIZ', models.ImageField(blank=True, null=True, upload_to='')),
                ('GDIN', models.CharField(blank=True, max_length=10, null=True)),
                ('GSTAT', models.CharField(blank=True, max_length=10, null=True)),
                ('NPLAST', models.CharField(blank=True, max_length=10, null=True)),
                ('NGIDK', models.CharField(blank=True, max_length=10, null=True)),
                ('KOLTK', models.CharField(blank=True, max_length=10, null=True)),
                ('DTK', models.CharField(blank=True, max_length=50, null=True)),
                ('IMP', models.BooleanField(blank=True, null=True)),
                ('GOST', models.CharField(blank=True, max_length=255, null=True)),
                ('STEEL', models.CharField(blank=True, max_length=255, null=True)),
                ('SREDN', models.FloatField(blank=True, null=True)),
                ('ZAVODS', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bearing', models.CharField(blank=True, max_length=100, verbose_name='Подшипник')),
                ('kolwo', models.IntegerField(verbose_name='Количество')),
                ('cena', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Стоимость')),
                ('sales', models.CharField(blank=True, max_length=100, verbose_name='Поставщик')),
                ('reserv', models.IntegerField(verbose_name='Резерв')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
    ]
